### PR TITLE
Fix issue with singular days/months

### LINKED ISSUE #27: [BUG] Selecting Events cross months
When you select events with dates that span across months, you get the following error:

message: "Server returned HTTP response code: 400 for URL: https://app.ticketmaster.com/discovery/v2/events.json?geoPoint=u4xsudc0f&radius=5&unit=km&startDateTime=2019-11-27T00%3A00%3A00Z&endDateTime=2019-12-3T23%3A59%3A59Z&apikey=PXLz8SSxwRDS9HUxwZ9LVAkQELNMbma8"

or 

  "message": "Server returned HTTP response code: 400 for URL: https://app.ticketmaster.com/discovery/v2/events.json?geoPoint\u003du4xsudc0f\u0026radius\u003d5\u0026unit\u003dkm\u0026startDateTime\u003d2019-11-28T00%3A00%3A00Z\u0026endDateTime\u003d2020-11-4T23%3A59%3A59Z\u0026apikey\u003dPXLz8SSxwRDS9HUxwZ9LVAkQELNMbma8"

It looks like the parsing of the date goes wrong somehow?

**To Reproduce**
1. Go to http://localhost:3000/#/date
2. Open Modal
3. Select a start date in one month, and an end date in another. 

**Expected behavior**
Events should show. 

**Screenshots**
Selecting Date
image
Response
image

**Additional context**
Works fine for me if I select dates within the same month.

### PR DESCRIPTION
**Pull request by Runi-VN**
Fixes #27

- Added a utility class `Utility.js`
- Tested and working

### CODE REVIEW

**Review by MalteMagnussen — APPROVED** [review]

File: src/utilities.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+const parseDate = date => {
+	let month = date.getMonth() + 1; //0-indexed
+	let day = date.getDate();
+
+	if (month < 10) month = '0'.concat(month); //ticketmaster API requires "YYYY-MM-DD", this would be "YYYY-MM-D"
+	if (day < 10) day = '0'.concat(day);
```
Comment (Runi-VN) [inline src/utilities.js:6]: These are the changes worth looking at
